# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
# created-by: conda 24.11.3
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/blas-1.0-mkl.conda
https://conda.anaconda.org/pytorch/noarch/pytorch-mutex-1.0-cuda.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/_libgcc_mutex-0.1-main.conda
https://repo.anaconda.com/pkgs/main/linux-64/ca-certificates-2024.12.31-h06a4308_0.conda
https://conda.anaconda.org/nvidia/linux-64/cuda-cudart-12.1.105-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/cuda-cupti-12.1.105-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/cuda-nvrtc-12.1.105-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/cuda-nvtx-12.1.105-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/cuda-opencl-12.4.127-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/ld_impl_linux-64-2.40-h12ee557_0.conda
https://conda.anaconda.org/nvidia/linux-64/libcublas-12.1.0.26-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcufft-11.0.2.4-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcufile-1.9.1.3-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcurand-10.3.5.147-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcusolver-11.4.4.55-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libcusparse-12.0.2.55-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libnpp-12.0.2.50-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libnvjitlink-12.1.105-0.tar.bz2
https://conda.anaconda.org/nvidia/linux-64/libnvjpeg-12.1.1.14-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libstdcxx-ng-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/noarch/tzdata-2025a-h04d1e81_0.conda
https://conda.anaconda.org/nvidia/linux-64/cuda-libraries-12.1.0-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgomp-11.2.0-h1234567_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/_openmp_mutex-5.1-1_gnu.conda
https://conda.anaconda.org/nvidia/linux-64/cuda-runtime-12.1.0-0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/libgcc-ng-11.2.0-h1234567_1.conda
https://conda.anaconda.org/pytorch/linux-64/pytorch-cuda-12.1-ha16c6d3_6.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/bzip2-1.0.8-h5eee18b_6.conda
https://conda.anaconda.org/nvidia/linux-64/cudatoolkit-11.7.0-hd8887f6_10.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/gmp-6.3.0-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libffi-3.4.4-h6a678d5_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/libsodium-1.0.18-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/libuuid-1.41.5-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ncurses-6.4-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/openssl-3.0.15-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tbb-2021.8.0-hdb19cb5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/xz-5.4.6-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/yaml-0.2.5-h7b6447c_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.13-h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/intel-openmp-2023.1.0-hdb19cb5_46306.conda
https://repo.anaconda.com/pkgs/main/linux-64/llvm-openmp-14.0.6-h9e868ea_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mpfr-4.2.1-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/readline-8.2-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/tk-8.6.14-h39e8969_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/zeromq-4.3.5-h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mkl-2023.1.0-h213fc3f_46344.conda
https://repo.anaconda.com/pkgs/main/linux-64/mpc-1.3.1-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.45.3-h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-3.11.11-he870216_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/debugpy-1.8.11-py311h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/decorator-5.1.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/executing-0.8.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/filelock-3.13.1-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/gmpy2-2.2.1-py311h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/markupsafe-3.0.2-py311h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/mpmath-1.3.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/nest-asyncio-1.6.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/networkx-3.4.2-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/packaging-24.2-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/parso-0.8.4-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/platformdirs-3.10.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/psutil-5.9.0-py311h5eee18b_1.conda
https://repo.anaconda.com/pkgs/main/noarch/ptyprocess-0.7.0-pyhd3eb1b0_2.conda
https://repo.anaconda.com/pkgs/main/noarch/pure_eval-0.2.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pygments-2.15.1-py311h06a4308_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyyaml-6.0.2-py311h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/pyzmq-26.2.0-py311h6a678d5_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/setuptools-75.8.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/tornado-6.4.2-py311h5eee18b_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/traitlets-5.14.3-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/typing_extensions-4.12.2-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/wcwidth-0.2.5-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/wheel-0.45.1-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/asttokens-2.0.5-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/comm-0.2.1-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jedi-0.19.2-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jinja2-3.1.5-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/jupyter_core-5.7.2-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/matplotlib-inline-0.1.6-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pexpect-4.8.0-pyhd3eb1b0_3.conda
https://repo.anaconda.com/pkgs/main/linux-64/pip-25.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/prompt-toolkit-3.0.43-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/python-dateutil-2.9.0post0-py311h06a4308_2.conda
https://repo.anaconda.com/pkgs/main/linux-64/jupyter_client-8.6.3-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/prompt_toolkit-3.0.43-hd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/stack_data-0.2.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ipython-8.30.0-py311h06a4308_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/ipykernel-6.29.5-py311h06a4308_1.conda
